### PR TITLE
feat(gen): const from default

### PR DESCRIPTION
**Pull request by sh0rez**
Generates a matching const for each type definition that holds the defaults for the type based on information from CUE defaults.

**Status**: Useful (I guess)

<table style="width:100%">
<tr>
<th>CUE</th>
<th>TS</th>
</tr>
<tr>
<td>

```go
package cuetsy

AType: "foo" | "bar" | *"baz" @cuetsy(targetType="type")

Foo: {
  Bar: string | *"ohai"
  Baz: int | *4
  C: AType
} @cuetsy(targetType="interface")
```

</td>
<td>

```ts
export type AType = 'foo' | 'bar' | 'baz';
export const aTypeDefault: AType = 'baz'
export interface Foo {
  Bar: string;
  Baz: number;
  C: AType;
}
export const fooDefault: Foo = {
  Bar: 'ohai',
  Baz: 4,
  C: aTypeDefault,
}
```

</td>
</tr>
<tr>
<td>

```go
package cuetsy

OrEnum: "foo" | "bar" | *"baz" @cuetsy(targetType="enum")

StructEnum: {
   Walla: "laadeedaa" @cuetsy(enumDefault)
   run: "OMG"
} @cuetsy(targetType="enum")
```

</td>
<td>

```ts
export enum OrEnum {
  Bar = 'bar',
  Baz = 'baz',
  Foo = 'foo',
}
export const orEnumDefault: OrEnum = OrEnum.Baz
export enum StructEnum {
  Walla = 'laadeedaa',
  run = 'OMG',
}
export const structEnumDefault: StructEnum = StructEnum.Walla
```

</td>
</tr>
</table>

### CODE REVIEW

**Comment by ryantxu** [comment]
excellent!  2 questions:

1. can generating defaults be optional?  We will only want it for some types of objects  (namely, panelOptions and panelFieldConfig)
2. can the default name be lowercase? 
`export const fooDefault: Foo ...`

**Comment by sh0rez** [comment]
@sdboyer @ryantxu afaict it is mostly does what it is supposed to do. There are for sure rough edges, but it should be good enough for a first round of review

**Comment by ryantxu** [comment]
The results here look great!  

If it is possible to optionally tag interfaces that we want to generate a default that would be best -- for most types we do not want a default and it will just create noise bloat.  It is only the final full options objects where we want.  Perhaps:

```
} @cuetsy(targetType="interface", generateDefaults=true)
```

**Comment by sdboyer** [comment]
So, months later...

i'm trying to recall why it is that we thought struct representations of enums were a good idea. I think it was because we were looking for a way to encode arbitrary member names easily. But it's just wrong. CUE structs are plainly, _not_ analogous to a TS enum. In a system (like we have in Grafana), using the CUE struct representation directly in some larger CUE structure means that you'll end up with a struct type on the CUE side, and an enum on the TS side. Not what we want.

The rest of this looks good, but i think that part's just not what we need. i introduced [an alternative pattern](https://github.com/grafana/grafana/pull/37857/files#diff-279feda2afcd43dcb2ae29a39aa2ab9fbf36fae988f968b89030b88e0b90235cR39) that seems like it should give us the same control (even if it's a bit awkward), while having a CUE type (simple disjunct value) which is harmonious with the TS it will become.

**Comment by sdboyer** [comment]
> i'm trying to recall why it is that we thought struct representations of enums were a good idea.

Well, it was literally the first issue - #1. Not the fault of this PR. So i'm gonna merge this one as-is, then we can pull that behavior out.

**Pull request merged**
